/* ===========================================================
   Noor Accessories - Complete EN / UR translation dictionary
   -----------------------------------------------------------
   Every visible string lives here. To translate a new label:
   1. add a key under BOTH `en` and `ur`
   2. in the HTML write  data-i18n="your.key"
   (placeholders use data-i18n-ph, titles use data-i18n-title)
   =========================================================== */

const TRANSLATIONS = {

  /* ================= ENGLISH ================= */
  en: {
    meta: { dir: 'ltr', name: 'English', flag: '🇬🇧', other: 'اردو', otherFlag: '🇵🇰' },

    /* --- header / nav --- */
    'nav.home'        : 'Home',
    'nav.products'    : 'Products',
    'nav.reviews'     : 'Reviews',
    'nav.about'       : 'About',
    'nav.search'      : 'Search',
    'nav.searchPh'    : 'Search accessories...',
    'nav.cart'        : 'Shopping Cart',
    'nav.profile'     : 'My Profile',
    'nav.whatsapp'    : 'WhatsApp',
    'nav.admin'       : 'Admin',
    'nav.menu'        : 'Menu',
    'nav.theme'       : 'Dark mode',

    /* --- hero --- */
    'hero.badge'      : 'New Collection 2026',
    'hero.title'      : 'Noor Accessories',
    'hero.tagline'    : 'Premium accessories for every beautiful moment',
    'hero.sub'        : 'Jewellery, bags, watches and more — delivered to your doorstep across Pakistan.',
    'hero.shopNow'    : 'Shop Now',
    'hero.chat'       : 'Chat on WhatsApp',
    'hero.stat1'      : 'Happy Customers',
    'hero.stat2'      : 'Products',
    'hero.stat3'      : 'Day Delivery',

    /* --- features strip --- */
    'feat.delivery'      : 'Fast Delivery',
    'feat.deliveryDesc'  : 'All over Pakistan',
    'feat.cod'           : 'Cash on Delivery',
    'feat.codDesc'       : 'Pay when you receive',
    'feat.quality'       : 'Premium Quality',
    'feat.qualityDesc'   : 'Hand-picked items',
    'feat.support'       : 'WhatsApp Support',
    'feat.supportDesc'   : 'We reply quickly',

    /* --- products --- */
    'prod.sectionTitle' : 'Our Collection',
    'prod.sectionSub'   : 'Find Your Perfect Accessory',
    'prod.allCategories': 'All Categories',
    'prod.sortBy'       : 'Sort by',
    'prod.sortNewest'   : 'Newest First',
    'prod.sortLowHigh'  : 'Price: Low to High',
    'prod.sortHighLow'  : 'Price: High to Low',
    'prod.sortPopular'  : 'Most Popular',
    'prod.addToCart'    : 'Add to Cart',
    'prod.viewDetails'  : 'View Details',
    'prod.inStock'      : 'In Stock',
    'prod.outOfStock'   : 'Out of Stock',
    'prod.available'    : 'Available',
    'prod.off'          : 'OFF',
    'prod.youSave'      : 'You save',
    'prod.category'     : 'Category',
    'prod.description'  : 'Description',
    'prod.quantity'     : 'Quantity',
    'prod.none'         : 'No products available',
    'prod.noneSub'      : 'Please check back soon or contact us on WhatsApp.',
    'prod.loading'      : 'Loading products...',
    'prod.results'      : 'products found',
    'prod.wishAdd'      : 'Add to wishlist',

    /* --- cart --- */
    'cart.title'      : 'Shopping Cart',
    'cart.empty'      : 'Your cart is empty',
    'cart.emptySub'   : 'Add some beautiful accessories to get started.',
    'cart.remove'     : 'Remove',
    'cart.quantity'   : 'Quantity',
    'cart.subtotal'   : 'Subtotal',
    'cart.discount'   : 'Discount',
    'cart.shipping'   : 'Shipping',
    'cart.free'       : 'FREE',
    'cart.total'      : 'Total',
    'cart.checkout'   : 'Proceed to Checkout',
    'cart.continue'   : 'Continue Shopping',
    'cart.clear'      : 'Clear Cart',
    'cart.added'      : 'Added to cart',
    'cart.removed'    : 'Removed from cart',

    /* --- checkout --- */
    'co.title'        : 'Checkout',
    'co.subtitle'     : 'Please fill in your delivery details',
    'co.name'         : 'Full Name',
    'co.namePh'       : 'e.g. Ayesha Khan',
    'co.phone'        : 'Phone Number',
    'co.phonePh'      : '03XX-XXXXXXX',
    'co.email'        : 'Email Address',
    'co.emailPh'      : 'you@example.com (optional)',
    'co.address'      : 'Delivery Address',
    'co.addressPh'    : 'House / street / area',
    'co.city'         : 'City',
    'co.cityPh'       : 'e.g. Lahore',
    'co.notes'        : 'Order Notes',
    'co.notesPh'      : 'Anything we should know? (optional)',
    'co.payment'      : 'Payment Method',
    'co.jazzcash'     : 'JazzCash',
    'co.easypaisa'    : 'Easypaisa',
    'co.cod'          : 'Cash on Delivery',
    'co.instructions' : 'Payment Instructions',
    'co.sendTo'       : 'Send the total amount to this number and share the screenshot on WhatsApp:',
    'co.accountTitle' : 'Account Title',
    'co.accountNumber': 'Mobile Number',
    'co.codNote'      : 'Pay the rider in cash when your parcel arrives.',
    'co.summary'      : 'Order Summary',
    'co.place'        : 'Place Order',
    'co.placing'      : 'Placing your order...',
    'co.back'         : 'Back to Cart',

    /* --- order confirmation --- */
    'oc.title'        : 'Order Confirmation',
    'oc.thanks'       : 'Thank you for your order!',
    'oc.orderId'      : 'Order ID',
    'oc.deliverIn'    : 'Will be delivered in',
    'oc.days'         : 'days',
    'oc.whatsapp'     : 'Send Order on WhatsApp',
    'oc.done'         : 'Continue Shopping',
    'oc.saved'        : 'Your order has been saved. We will contact you shortly.',

    /* --- profile --- */
    'pf.title'        : 'My Profile',
    'pf.tabInfo'      : 'Profile Info',
    'pf.tabOrders'    : 'My Orders',
    'pf.tabReviews'   : 'Remarks & Reviews',
    'pf.tabWishlist'  : 'Wishlist',
    'pf.name'         : 'Full Name',
    'pf.email'        : 'Email Address',
    'pf.phone'        : 'Phone Number',
    'pf.city'         : 'City',
    'pf.address'      : 'Delivery Address',
    'pf.language'     : 'Preferred Language',
    'pf.save'         : 'Save Changes',
    'pf.saved'        : 'Profile updated successfully',
    'pf.orderDate'    : 'Order Date',
    'pf.orderStatus'  : 'Order Status',
    'pf.items'        : 'Items',
    'pf.noOrders'     : 'No orders yet',
    'pf.noOrdersSub'  : 'Your orders will appear here once you place one.',
    'pf.loadOrders'   : 'Refresh from store',
    'pf.emptyWish'    : 'Your wishlist is empty',
    'pf.yourRemarks'  : 'Your Remarks / Feedback',
    'pf.remarksPh'    : 'Share your thoughts about our products and service...',
    'pf.rating'       : 'Rating',
    'pf.submit'       : 'Submit Feedback',
    'pf.thanks'       : 'Thank you for your feedback',

    /* --- order status --- */
    'st.pending'      : 'Pending',
    'st.confirmed'    : 'Confirmed',
    'st.shipped'      : 'Shipped',
    'st.completed'    : 'Completed',
    'st.cancelled'    : 'Cancelled',

    /* --- reviews --- */
    'rv.title'        : 'What Our Customers Say',
    'rv.sub'          : 'Customer Reviews',
    'rv.none'         : 'No reviews yet',
    'rv.noneSub'      : 'Be the first to share your experience.',
    'rv.write'        : 'Write a Review',
    'rv.average'      : 'Average Rating',

    /* --- footer --- */
    'ft.about'        : 'About Noor Accessories',
    'ft.aboutText'    : 'Premium quality accessories for ladies — jewellery, bags, watches and more, hand-picked with love and delivered across Pakistan.',
    'ft.links'        : 'Quick Links',
    'ft.contact'      : 'Contact Us',
    'ft.whatsappOnly' : 'WhatsApp Only',
    'ft.chat'         : 'Chat on WhatsApp',
    'ft.follow'       : 'Follow Us',
    'ft.rights'       : 'All rights reserved',
    'ft.hours'        : 'Open daily 10:00 AM – 10:00 PM',
    'ft.adEnquiries'  : 'For advertising & bulk orders',

    /* --- admin --- */
    'ad.login'        : 'Admin Login',
    'ad.loginSub'     : 'Please sign in to manage your store',
    'ad.username'     : 'Username',
    'ad.usernamePh'   : 'Enter username',
    'ad.password'     : 'Password',
    'ad.passwordPh'   : 'Enter password',
    'ad.signIn'       : 'Sign In',
    'ad.logout'       : 'Logout',
    'ad.dashboard'    : 'Dashboard',
    'ad.welcome'      : 'Welcome Admin',
    'ad.totalProducts': 'Total Products',
    'ad.totalOrders'  : 'Total Orders',
    'ad.totalCustomers':'Total Customers',
    'ad.totalRevenue' : 'Total Revenue',
    'ad.avgRating'    : 'Average Rating',
    'ad.pendingOrders': 'Pending Orders',
    'ad.tabProducts'  : 'Products',
    'ad.tabOrders'    : 'Orders',
    'ad.tabCustomers' : 'Customers',
    'ad.tabReviews'   : 'Reviews',
    'ad.addProduct'   : 'Add Product',
    'ad.newProduct'   : 'New Product',
    'ad.nameEn'       : 'Name (English)',
    'ad.nameUr'       : 'Name (Urdu)',
    'ad.descEn'       : 'Short Description (English)',
    'ad.descUr'       : 'Short Description (Urdu)',
    'ad.price'        : 'Price',
    'ad.originalPrice': 'Original Price',
    'ad.imageUrl'     : 'Image URL',
    'ad.stock'        : 'Quantity',
    'ad.status'       : 'Status',
    'ad.actions'      : 'Actions',
    'ad.customer'     : 'Customer',
    'ad.date'         : 'Date',
    'ad.amount'       : 'Amount',
    'ad.invalid'      : 'Invalid credentials',
    'ad.backToStore'  : 'Back to Store',
    'ad.noData'       : 'No data yet',
    'ad.demoNote'     : 'Demo mode — connect your Google Sheet in js/config.js to manage live data.',
    'ad.overview'     : 'Overview',
    'ad.search'       : 'Search',
    'ad.searchProducts': 'Search products...',
    'ad.searchOrders' : 'Search by name, phone or order ID...',
    'ad.searchCustomers': 'Search customers...',
    'ad.editProduct'  : 'Edit Product',
    'ad.saveProduct'  : 'Save Product',
    'ad.saving'       : 'Saving...',
    'ad.added'        : 'Product added',
    'ad.updated'      : 'Product updated',
    'ad.deleted'      : 'Product deleted',
    'ad.statusSaved'  : 'Order status updated',
    'ad.confirmTitle' : 'Delete this product?',
    'ad.confirmBody'  : 'It will be removed from your store and your Google Sheet. This cannot be undone.',
    'ad.yesDelete'    : 'Yes, delete',
    'ad.preview'      : 'Preview',
    'ad.discountAuto' : 'Discount is worked out for you',
    'ad.imageHint'    : 'Paste a link, or use assets/products/name.jpg for a file in your repo',
    'ad.noResults'    : 'Nothing matches that search',
    'ad.allStatus'    : 'All statuses',
    'ad.allCats'      : 'All categories',
    'ad.waCustomer'   : 'WhatsApp customer',
    'ad.lowStock'     : 'Low stock',
    'ad.sold'         : 'sold',
    'ad.left'         : 'left',
    'ad.refresh'      : 'Refresh',
    'ad.required'     : 'Please fill in the name and price',
    'ad.quickStock'   : 'Stock',
    'ad.lastOrders'   : 'Latest orders',
    'ad.lowStockTitle': 'Running low',
    'ad.allGood'      : 'Everything is well stocked',
    'ad.viewAll'      : 'View all',
    'car.prev'        : 'Previous slide',
    'car.next'        : 'Next slide',
    'car.play'        : 'Play video',
    'ad.tabBanners'   : 'Carousel',
    'ad.addBanner'    : 'Add Slide',
    'ad.newBanner'    : 'New Slide',
    'ad.editBanner'   : 'Edit Slide',
    'ad.slideType'    : 'Slide type',
    'ad.typeImage'    : 'Photo',
    'ad.typeVideo'    : 'Video',
    'ad.slideTitleEn' : 'Headline (English)',
    'ad.slideTitleUr' : 'Headline (Urdu)',
    'ad.slideSubEn'   : 'Sub-line (English)',
    'ad.slideSubUr'   : 'Sub-line (Urdu)',
    'ad.mediaUrl'     : 'Photo or video link',
    'ad.mediaHint'    : 'assets/products/ns02.jpg, an .mp4 link, or a YouTube link',
    'ad.posterUrl'    : 'Video cover image',
    'ad.linkUrl'      : 'Button goes to',
    'ad.btnEn'        : 'Button text (English)',
    'ad.btnUr'        : 'Button text (Urdu)',
    'ad.sortOrder'    : 'Position',
    'ad.confirmSlide' : 'Delete this slide?',
    'ad.bannerSaved'  : 'Slide saved',
    'ad.bannerDeleted': 'Slide deleted',
    'ad.noBanners'    : 'No slides yet — add one to start the carousel',
    'ad.pushSheet'    : 'Reset Sheet to this catalogue',
    'ad.confirmPush'  : 'Replace the products in your Google Sheet?',
    'ad.yesReplace'   : 'Yes, replace',
    'ad.pushing'      : 'Sending to your Google Sheet...',
    'ad.pushDone'     : 'Your Google Sheet now matches this catalogue',
    'ad.pushNeedsSheet': 'Connect your Google Sheet first (js/config.js)',
    'ad.export'       : 'Export CSV',
    'ad.openSheet'    : 'Open Google Sheet',

    /* --- generic --- */
    'g.shopNow'   : 'Shop Now',
    'g.edit'      : 'Edit',
    'g.delete'    : 'Delete',
    'g.save'      : 'Save',
    'g.cancel'    : 'Cancel',
    'g.close'     : 'Close',
    'g.loading'   : 'Loading',
    'g.error'     : 'Error',
    'g.success'   : 'Success',
    'g.required'  : 'This field is required',
    'g.badPhone'  : 'Please enter a valid phone number',
    'g.badEmail'  : 'Please enter a valid email address',
    'g.offline'   : 'Could not reach the store. Showing saved data.',
    'g.demoMode'  : 'Demo mode: sample products are shown. Connect Google Sheets in js/config.js.',
    'g.currency'  : 'Rs.'
  },

  /* ================= اردو ================= */
  ur: {
    meta: { dir: 'rtl', name: 'اردو', flag: '🇵🇰', other: 'English', otherFlag: '🇬🇧' },

    'nav.home'        : 'گھر',
    'nav.products'    : 'مصنوعات',
    'nav.reviews'     : 'تبصرے',
    'nav.about'       : 'ہمارے بارے میں',
    'nav.search'      : 'تلاش کریں',
    'nav.searchPh'    : 'سہولیات تلاش کریں...',
    'nav.cart'        : 'شاپنگ کارٹ',
    'nav.profile'     : 'میرا پروفائل',
    'nav.whatsapp'    : 'واٹس ایپ',
    'nav.admin'       : 'ایڈمن',
    'nav.menu'        : 'مینو',
    'nav.theme'       : 'ڈارک موڈ',

    'hero.badge'      : 'نیا کلیکشن 2026',
    'hero.title'      : 'نور ایکسیسریز',
    'hero.tagline'    : 'ہر خوبصورت لمحے کے لیے معیاری سہولیات',
    'hero.sub'        : 'زیورات، بیگ، گھڑیاں اور بہت کچھ — پورے پاکستان میں آپ کے دروازے تک۔',
    'hero.shopNow'    : 'اب خریدیں',
    'hero.chat'       : 'واٹس ایپ پر بات کریں',
    'hero.stat1'      : 'خوش گاہک',
    'hero.stat2'      : 'مصنوعات',
    'hero.stat3'      : 'دن میں ترسیل',

    'feat.delivery'      : 'تیز ترسیل',
    'feat.deliveryDesc'  : 'پورے پاکستان میں',
    'feat.cod'           : 'روپے پر ترسیل',
    'feat.codDesc'       : 'سامان ملنے پر ادائیگی',
    'feat.quality'       : 'معیاری مصنوعات',
    'feat.qualityDesc'   : 'چُنی ہوئی اشیاء',
    'feat.support'       : 'واٹس ایپ سپورٹ',
    'feat.supportDesc'   : 'ہم جلد جواب دیتے ہیں',

    'prod.sectionTitle' : 'ہمارا کلیکشن',
    'prod.sectionSub'   : 'اپنی بہترین سہولت تلاش کریں',
    'prod.allCategories': 'تمام زمرہ جات',
    'prod.sortBy'       : 'ترتیب دیں',
    'prod.sortNewest'   : 'نیا پہلے',
    'prod.sortLowHigh'  : 'سستا سے مہنگا',
    'prod.sortHighLow'  : 'مہنگا سے سستا',
    'prod.sortPopular'  : 'سب سے مشہور',
    'prod.addToCart'    : 'کارٹ میں شامل کریں',
    'prod.viewDetails'  : 'تفصیلات دیکھیں',
    'prod.inStock'      : 'اسٹاک میں',
    'prod.outOfStock'   : 'اسٹاک ختم',
    'prod.available'    : 'دستیاب',
    'prod.off'          : 'رعایت',
    'prod.youSave'      : 'آپ کی بچت',
    'prod.category'     : 'زمرہ',
    'prod.description'  : 'تفصیل',
    'prod.quantity'     : 'مقدار',
    'prod.none'         : 'کوئی مصنوعات دستیاب نہیں',
    'prod.noneSub'      : 'براہ کرم کچھ دیر بعد دیکھیں یا واٹس ایپ پر رابطہ کریں۔',
    'prod.loading'      : 'مصنوعات لوڈ ہو رہی ہیں...',
    'prod.results'      : 'مصنوعات ملیں',
    'prod.wishAdd'      : 'پسندیدہ میں شامل کریں',

    'cart.title'      : 'شاپنگ کارٹ',
    'cart.empty'      : 'آپ کی کارٹ خالی ہے',
    'cart.emptySub'   : 'شروع کرنے کے لیے کچھ خوبصورت سہولیات شامل کریں۔',
    'cart.remove'     : 'ہٹائیں',
    'cart.quantity'   : 'مقدار',
    'cart.subtotal'   : 'کل رقم',
    'cart.discount'   : 'رعایت',
    'cart.shipping'   : 'ترسیل کے اخراجات',
    'cart.free'       : 'مفت',
    'cart.total'      : 'کل',
    'cart.checkout'   : 'چیک آؤٹ جاری رکھیں',
    'cart.continue'   : 'خریداری جاری رکھیں',
    'cart.clear'      : 'کارٹ خالی کریں',
    'cart.added'      : 'کارٹ میں شامل کیا گیا',
    'cart.removed'    : 'کارٹ سے ہٹا دیا گیا',

    'co.title'        : 'ادائیگی کے لیے آگے بڑھیں',
    'co.subtitle'     : 'براہ کرم ترسیل کی تفصیلات درج کریں',
    'co.name'         : 'مکمل نام',
    'co.namePh'       : 'مثلاً عائشہ خان',
    'co.phone'        : 'فون نمبر',
    'co.phonePh'      : '03XX-XXXXXXX',
    'co.email'        : 'ای میل پتہ',
    'co.emailPh'      : 'you@example.com (اختیاری)',
    'co.address'      : 'ترسیل کا پتہ',
    'co.addressPh'    : 'گھر / گلی / علاقہ',
    'co.city'         : 'شہر',
    'co.cityPh'       : 'مثلاً لاہور',
    'co.notes'        : 'آرڈر کے بارے میں نوٹ',
    'co.notesPh'      : 'کچھ بتانا چاہیں گی؟ (اختیاری)',
    'co.payment'      : 'ادائیگی کا طریقہ',
    'co.jazzcash'     : 'جاز کیش',
    'co.easypaisa'    : 'ای پیسہ',
    'co.cod'          : 'روپے پر ترسیل',
    'co.instructions' : 'ادائیگی کی ہدایات',
    'co.sendTo'       : 'کل رقم اس نمبر پر بھیجیں اور اسکرین شاٹ واٹس ایپ پر شیئر کریں:',
    'co.accountTitle' : 'اکاؤنٹ کا نام',
    'co.accountNumber': 'موبائل نمبر',
    'co.codNote'      : 'پارسل ملنے پر رائیڈر کو نقد ادائیگی کریں۔',
    'co.summary'      : 'آرڈر کا خلاصہ',
    'co.place'        : 'آرڈر دیں',
    'co.placing'      : 'آپ کا آرڈر دیا جا رہا ہے...',
    'co.back'         : 'کارٹ پر واپس',

    'oc.title'        : 'آرڈر کی تصدیق',
    'oc.thanks'       : 'آپ کے آرڈر کا شکریہ!',
    'oc.orderId'      : 'آرڈر نمبر',
    'oc.deliverIn'    : 'میں ترسیل ہوگی',
    'oc.days'         : 'دن',
    'oc.whatsapp'     : 'واٹس ایپ پر آرڈر بھیجیں',
    'oc.done'         : 'خریداری جاری رکھیں',
    'oc.saved'        : 'آپ کا آرڈر محفوظ ہو گیا ہے۔ ہم جلد رابطہ کریں گے۔',

    'pf.title'        : 'میرا پروفائل',
    'pf.tabInfo'      : 'پروفائل کی معلومات',
    'pf.tabOrders'    : 'میرے آرڈرز',
    'pf.tabReviews'   : 'تبصرے اور رائے',
    'pf.tabWishlist'  : 'پسندیدہ',
    'pf.name'         : 'مکمل نام',
    'pf.email'        : 'ای میل پتہ',
    'pf.phone'        : 'فون نمبر',
    'pf.city'         : 'شہر',
    'pf.address'      : 'ترسیل کا پتہ',
    'pf.language'     : 'پسندیدہ زبان',
    'pf.save'         : 'تبدیلیاں محفوظ کریں',
    'pf.saved'        : 'پروفائل کامیابی سے اپ ڈیٹ ہوا',
    'pf.orderDate'    : 'آرڈر کی تاریخ',
    'pf.orderStatus'  : 'آرڈر کی حالت',
    'pf.items'        : 'اشیاء',
    'pf.noOrders'     : 'ابھی کوئی آرڈرز نہیں',
    'pf.noOrdersSub'  : 'آرڈر دینے کے بعد یہاں نظر آئے گا۔',
    'pf.loadOrders'   : 'اسٹور سے تازہ کریں',
    'pf.emptyWish'    : 'آپ کی پسندیدہ فہرست خالی ہے',
    'pf.yourRemarks'  : 'آپ کے تبصرے / رائے',
    'pf.remarksPh'    : 'اپنے خیالات شیئر کریں...',
    'pf.rating'       : 'درجہ بندی',
    'pf.submit'       : 'رائے جمع کریں',
    'pf.thanks'       : 'آپ کی رائے کے لیے شکریہ',

    'st.pending'      : 'زیر التوا',
    'st.confirmed'    : 'تصدیق شدہ',
    'st.shipped'      : 'روانہ کر دیا گیا',
    'st.completed'    : 'مکمل شدہ',
    'st.cancelled'    : 'منسوخ شدہ',

    'rv.title'        : 'ہمارے گاہکوں کا کہنا ہے',
    'rv.sub'          : 'گاہکوں کے تبصرے',
    'rv.none'         : 'ابھی کوئی تبصرہ نہیں',
    'rv.noneSub'      : 'سب سے پہلے اپنا تجربہ شیئر کریں۔',
    'rv.write'        : 'تبصرہ لکھیں',
    'rv.average'      : 'اوسط درجہ بندی',

    'ft.about'        : 'نور ایکسیسریز کے بارے میں',
    'ft.aboutText'    : 'خواتین کے لیے معیاری سہولیات — زیورات، بیگ، گھڑیاں اور بہت کچھ، محبت سے چُنی گئی اور پورے پاکستان میں فراہم کی جاتی ہیں۔',
    'ft.links'        : 'فوری روابط',
    'ft.contact'      : 'ہم سے رابطہ کریں',
    'ft.whatsappOnly' : 'صرف واٹس ایپ',
    'ft.chat'         : 'واٹس ایپ پر بات کریں',
    'ft.follow'       : 'ہمیں فالو کریں',
    'ft.rights'       : 'تمام حقوق محفوظ ہیں',
    'ft.hours'        : 'روزانہ صبح 10:00 تا رات 10:00 کھلا ہے',
    'ft.adEnquiries'  : 'اشتہار اور تھوک آرڈر کے لیے',

    'ad.login'        : 'ایڈمن لاگ ان',
    'ad.loginSub'     : 'اسٹور کے انتظام کے لیے سائن ان کریں',
    'ad.username'     : 'صارف نام',
    'ad.usernamePh'   : 'صارف نام درج کریں',
    'ad.password'     : 'پاس ورڈ',
    'ad.passwordPh'   : 'پاس ورڈ درج کریں',
    'ad.signIn'       : 'سائن ان',
    'ad.logout'       : 'لاگ آؤٹ',
    'ad.dashboard'    : 'ڈیش بورڈ',
    'ad.welcome'      : 'ایڈمن کو خوش آمدید',
    'ad.totalProducts': 'کل مصنوعات',
    'ad.totalOrders'  : 'کل آرڈرز',
    'ad.totalCustomers':'کل گاہک',
    'ad.totalRevenue' : 'کل آمدنی',
    'ad.avgRating'    : 'اوسط درجہ بندی',
    'ad.pendingOrders': 'زیر التوا آرڈرز',
    'ad.tabProducts'  : 'مصنوعات',
    'ad.tabOrders'    : 'آرڈرز',
    'ad.tabCustomers' : 'گاہک',
    'ad.tabReviews'   : 'تبصرے',
    'ad.addProduct'   : 'مصنوعات شامل کریں',
    'ad.newProduct'   : 'نئی مصنوعات',
    'ad.nameEn'       : 'نام (انگریزی)',
    'ad.nameUr'       : 'نام (اردو)',
    'ad.descEn'       : 'مختصر تفصیل (انگریزی)',
    'ad.descUr'       : 'مختصر تفصیل (اردو)',
    'ad.price'        : 'قیمت',
    'ad.originalPrice': 'اصل قیمت',
    'ad.imageUrl'     : 'تصویر کا لنک',
    'ad.stock'        : 'مقدار',
    'ad.status'       : 'حالت',
    'ad.actions'      : 'اعمال',
    'ad.customer'     : 'گاہک',
    'ad.date'         : 'تاریخ',
    'ad.amount'       : 'رقم',
    'ad.invalid'      : 'غلط صارف نام یا پاس ورڈ',
    'ad.backToStore'  : 'اسٹور پر واپس',
    'ad.noData'       : 'ابھی کوئی ڈیٹا نہیں',
    'ad.demoNote'     : 'ڈیمو موڈ — لائیو ڈیٹا کے لیے js/config.js میں اپنی گوگل شیٹ جوڑیں۔',
    'ad.overview'     : 'خلاصہ',
    'ad.search'       : 'تلاش',
    'ad.searchProducts': 'مصنوعات تلاش کریں...',
    'ad.searchOrders' : 'نام، فون یا آرڈر نمبر سے تلاش کریں...',
    'ad.searchCustomers': 'گاہک تلاش کریں...',
    'ad.editProduct'  : 'مصنوعات میں ترمیم',
    'ad.saveProduct'  : 'مصنوعات محفوظ کریں',
    'ad.saving'       : 'محفوظ ہو رہا ہے...',
    'ad.added'        : 'مصنوعات شامل ہو گئی',
    'ad.updated'      : 'مصنوعات اپ ڈیٹ ہو گئی',
    'ad.deleted'      : 'مصنوعات حذف ہو گئی',
    'ad.statusSaved'  : 'آرڈر کی حالت اپ ڈیٹ ہو گئی',
    'ad.confirmTitle' : 'یہ مصنوعات حذف کریں؟',
    'ad.confirmBody'  : 'یہ آپ کے اسٹور اور گوگل شیٹ دونوں سے ہٹ جائے گی۔ واپس نہیں لایا جا سکتا۔',
    'ad.yesDelete'    : 'جی ہاں، حذف کریں',
    'ad.preview'      : 'نمونہ',
    'ad.discountAuto' : 'رعایت خود بخود شمار ہو جائے گی',
    'ad.imageHint'    : 'لنک لگائیں، یا اپنی فائل کے لیے assets/products/name.jpg لکھیں',
    'ad.noResults'    : 'اس تلاش سے کچھ نہیں ملا',
    'ad.allStatus'    : 'تمام حالتیں',
    'ad.allCats'      : 'تمام زمرہ جات',
    'ad.waCustomer'   : 'گاہک کو واٹس ایپ کریں',
    'ad.lowStock'     : 'اسٹاک کم ہے',
    'ad.sold'         : 'فروخت',
    'ad.left'         : 'باقی',
    'ad.refresh'      : 'تازہ کریں',
    'ad.required'     : 'براہ کرم نام اور قیمت درج کریں',
    'ad.quickStock'   : 'اسٹاک',
    'ad.lastOrders'   : 'تازہ ترین آرڈرز',
    'ad.lowStockTitle': 'اسٹاک ختم ہو رہا ہے',
    'ad.allGood'      : 'تمام مصنوعات کا اسٹاک مناسب ہے',
    'ad.viewAll'      : 'سب دیکھیں',
    'car.prev'        : 'پچھلی سلائیڈ',
    'car.next'        : 'اگلی سلائیڈ',
    'car.play'        : 'ویڈیو چلائیں',
    'ad.tabBanners'   : 'کیروسل',
    'ad.addBanner'    : 'سلائیڈ شامل کریں',
    'ad.newBanner'    : 'نئی سلائیڈ',
    'ad.editBanner'   : 'سلائیڈ میں ترمیم',
    'ad.slideType'    : 'سلائیڈ کی قسم',
    'ad.typeImage'    : 'تصویر',
    'ad.typeVideo'    : 'ویڈیو',
    'ad.slideTitleEn' : 'سرخی (انگریزی)',
    'ad.slideTitleUr' : 'سرخی (اردو)',
    'ad.slideSubEn'   : 'ذیلی سطر (انگریزی)',
    'ad.slideSubUr'   : 'ذیلی سطر (اردو)',
    'ad.mediaUrl'     : 'تصویر یا ویڈیو کا لنک',
    'ad.mediaHint'    : 'assets/products/ns02.jpg، mp4. لنک، یا یوٹیوب لنک',
    'ad.posterUrl'    : 'ویڈیو کی سرورق تصویر',
    'ad.linkUrl'      : 'بٹن کہاں لے جائے',
    'ad.btnEn'        : 'بٹن کا متن (انگریزی)',
    'ad.btnUr'        : 'بٹن کا متن (اردو)',
    'ad.sortOrder'    : 'ترتیب',
    'ad.confirmSlide' : 'یہ سلائیڈ حذف کریں؟',
    'ad.bannerSaved'  : 'سلائیڈ محفوظ ہو گئی',
    'ad.bannerDeleted': 'سلائیڈ حذف ہو گئی',
    'ad.noBanners'    : 'ابھی کوئی سلائیڈ نہیں — کیروسل شروع کرنے کے لیے ایک شامل کریں',
    'ad.pushSheet'    : 'شیٹ کو اس کیٹلاگ سے بدلیں',
    'ad.confirmPush'  : 'گوگل شیٹ کی مصنوعات تبدیل کر دیں؟',
    'ad.yesReplace'   : 'جی ہاں، تبدیل کریں',
    'ad.pushing'      : 'آپ کی گوگل شیٹ میں بھیجا جا رہا ہے...',
    'ad.pushDone'     : 'آپ کی گوگل شیٹ اب اس کیٹلاگ کے مطابق ہے',
    'ad.pushNeedsSheet': 'پہلے اپنی گوگل شیٹ جوڑیں (js/config.js)',
    'ad.export'       : 'CSV ایکسپورٹ',
    'ad.openSheet'    : 'گوگل شیٹ کھولیں',

    'g.shopNow'   : 'اب خریدیں',
    'g.edit'      : 'ترمیم کریں',
    'g.delete'    : 'حذف کریں',
    'g.save'      : 'محفوظ کریں',
    'g.cancel'    : 'منسوخ کریں',
    'g.close'     : 'بند کریں',
    'g.loading'   : 'لوڈ ہو رہا ہے',
    'g.error'     : 'خرابی',
    'g.success'   : 'کامیاب',
    'g.required'  : 'یہ خانہ ضروری ہے',
    'g.badPhone'  : 'براہ کرم درست فون نمبر درج کریں',
    'g.badEmail'  : 'براہ کرم درست ای میل پتہ درج کریں',
    'g.offline'   : 'اسٹور تک رسائی نہیں ہو سکی۔ محفوظ ڈیٹا دکھایا جا رہا ہے۔',
    'g.demoMode'  : 'ڈیمو موڈ: نمونہ مصنوعات دکھائی جا رہی ہیں۔ js/config.js میں گوگل شیٹ جوڑیں۔',
    'g.currency'  : 'روپے'
  }
};

window.TRANSLATIONS = TRANSLATIONS;
